server.port=8081
spring.application.name=festora-payment-microservice

# Standard Razorpay Sandbox & Gateway API Config
razorpay.key.id=rzp_test_TIuNseQI3AsTL4
razorpay.key.secret=7adHuxgXMcT0mkCAESNrUYmc
