server.port=${PORT:8081}
spring.application.name=festora-payment-microservice

# Razorpay API Credentials (Loaded dynamically from .env / System Environment)
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_TIuNseQI3AsTL4}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:7adHuxgXMcT0mkCAESNrUYmc}
